### ISSUE TITLE
getting started developing with RacketScript?

### ISSUE THREAD

**Issue by spdegabrielle** [racketscript/racketscript#260]
Hi, my js is a bit rusty (that is the mild way to say I've not used it in 20 years)

What is the recommended IDE & development workflow for making a client side app in racket script?

**Comment by stchang** [comment]
Unfortunately, we don't really have our own abstractions or workflow yet.

So the app would have to call out to JS using the FFI and then follow standard js workflows.

As an example, you could look at the [racketscript playground implementation](https://github.com/racketscript/racketscript-playground/blob/master/app.rkt), which is a basic node.js express app.

There's also [Rackt](https://github.com/rackt-org/rackt) which is a wrapper for React, but I think you'd still have to understand React in order to use it.

So admittedly it might be more useful going through a few JS webapp tutorials first.

**Comment by spdegabrielle** [comment]
Thank you @stchang your advice is much appreciated!
